{% set name = "pymace" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ACEsuit/mace/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 806f21cd652c02e5b6278fbcb5c3f7dd931bb452141be9b8f43d4096639493c5

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  build:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pytorch >=1.12
    - e3nn =0.4.4
    - numpy
    - opt_einsum
    - ase
    - torch-ema
    - prettytable
    - matplotlib-base
    - pandas

test:
  imports:
    - mace
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ACEsuit/mace
  summary: 'MACE - Fast and accurate machine learning interatomic potentials with higher order equivariant message passing.'
  description: |
    MACE provides fast and accurate machine learning interatomic 
    potentials with higher order equivariant message passing. This 
    repository contains the MACE reference implementation developed 
    by Ilyes Batatia, Gregor Simm, and David Kovacs.
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  doc_url: https://github.com/ACEsuit/mace
  dev_url: https://github.com/ACEsuit/mace

extra:
  recipe-maintainers:
    - jan-janssen

